install.packages(c("ggplot2",
                   "dplyr",
                   "tidyr",
                   "rgl",
                   "lubridate",
                   "stringdist",
                   "fuzzyjoin",
                   "pracma",
                   "NbClust"))